### ISSUE TITLE
about the unit of some variables

### ISSUE THREAD

**Issue by leolyg** [emilbjornson/IRS-relaying#2]
Hi Prof. Emil Björnson,

Thank you for your code. It brings me a lot of help.
However, there is a problem that confuses me.
In simulateFigure2.m, you use the below code to calculate beta.
`
antennaGainTdBi = db2pow(5);
`
...
`
beta_3GPP_LOS = db2pow(antennaGainTdBi+antennaGainRdBi-28-20*log10(fc)-22*log10(d));
`
In simulateFigure4.m, you use another way.
`
antennaGainS = db2pow(5);
`
...
`
pathloss_3GPP_LOS = @(x) db2pow(-28-20*log10(fc)-22*log10(x));
`
...
`
betaSR = pathloss_3GPP_LOS(d_SR)*antennaGainS*antennaGainR;
`

I think `antennaGainTdBi ` has been transferred to mW, it can not be added.
I am not sure about it, hope for your reply.

Thank you.
leo

**Comment by emilbjornson** [comment]
You are right that there was an error in the code to Figure 2. The antenna gain should be 5 dBi, and not converted. It has been corrected now.
